In [134]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [135]:
from sklearn import datasets
from sklearn.metrics import r2_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [136]:
dataset=pd.read_csv('Multiple_Linear_Regression_Advertising_data.csv')
df = pd.DataFrame(dataset)
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [137]:
dataset.keys()

Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [138]:
dataset.TV[0]

230.1

In [139]:
dataset.Sales[0]

22.1

In [140]:
dataset.TV.shape

(200,)

In [141]:
dataset.Sales.shape

(200,)

In [142]:
print(df.head())
print("-------\n")

x = dataset.iloc[:,:-1].values
print(x[:5])

print("-------")


y = dataset.iloc[:, 3].values
print(y[:5])

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9
-------

[[230.1  37.8  69.2]
 [ 44.5  39.3  45.1]
 [ 17.2  45.9  69.3]
 [151.5  41.3  58.5]
 [180.8  10.8  58.4]]
-------
[22.1 10.4  9.3 18.5 12.9]


In [143]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=12)

In [144]:
x_test.shape


(40, 3)

In [145]:
regrassion = LinearRegression()

In [146]:
regrassion.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [147]:
regrassion.coef_

array([ 0.04452235,  0.19286187, -0.00465557])

In [148]:
regrassion.intercept_

3.088230171114791

In [149]:
y_predictions = regrassion.predict(x_test)

In [150]:
y_predictions[:5]

array([16.39007308,  6.55142872,  7.75824723, 14.53202646, 13.33028039])

In [151]:
print(x_train[:5],"\n")
print(x_test[:5],"\n")
print(y_train[:5],"\n")
print(y_test[:5])

[[120.5  28.5  14.2]
 [239.9  41.5  18.5]
 [107.4  14.   10.9]
 [204.1  32.9  46. ]
 [177.   33.4  38.7]] 

[[228.3  16.9  26.2]
 [ 56.2   5.7  29.7]
 [ 19.6  20.1  17. ]
 [237.4   5.1  23.5]
 [102.7  29.6   8.4]] 

[14.2 23.2 11.5 19.  17.1] 

[15.5  8.7  7.6 12.5 14. ]


In [152]:
#define plot

In [153]:
s= r2_score(y_test, y_predictions)
print("R2 score is : ",s)

R2 score is :  0.9125583321991082
